Bring openstack-pkg-tools to latest changes.
This commits changes that were not pushed to Gerrit previously,
but were in the Alioth git. This includes:

- Fix for the adm group and startup scrpts.
- Addition of postrm / prerm templates.
- Backquotes when altering db to use utf-8.
- pkgos-alioth-new-git using rsync instead of scp to allow resume.

Change-Id: Id28d3d66397286526a1bfc558ada5cc6b006200e

diff --git a/pkgos_func b/pkgos_func
--- a/pkgos_func
+++ b/pkgos_func
@@ -422,7 +422,7 @@ pkgos_dbc_postinst () {
 					fi
 					SQL_CONNECTION="mysql+pymysql://$dbc_dbuser:$dbc_dbpass@${dbc_dbserver:-localhost}$dbport/$dbc_dbname"
 					# Set the DB as UTF8
-					Q="ALTER DATABASE ${dbc_dbname} CHARACTER SET utf8 COLLATE utf8_unicode_ci"
+					Q="ALTER DATABASE \`${dbc_dbname}\` CHARACTER SET utf8 COLLATE utf8_unicode_ci"
 					pkgos_mysql_query ${dbc_dbuser} ${dbc_dbpass} ${dbc_dbserver:-localhost} "${dbport}" ${dbc_dbname} "${Q}"
 					;;
 				postgresql*|pgsql)
@@ -566,6 +566,9 @@ pkgos_var_user_group () {
 	VAR_UG_PKG_NAME=${1}
 	VAR_UG_SHELL=${2}
 
+	# Remove user from adm group, because we was adding it nonintentionally
+	deluser -q ${VAR_UG_PKG_NAME} adm 2>/dev/null || true
+
 	pkgos_adduser ${VAR_UG_PKG_NAME} ${VAR_UG_SHELL}
 
 	# Create /var/{lib,log}/<package> with that user/group if it doesn't exist
@@ -581,7 +584,6 @@ pkgos_var_user_group () {
 	if [ ! -d /var/log/${VAR_UG_PKG_NAME} ] ; then
 		mkdir -p /var/log/${VAR_UG_PKG_NAME}
 	fi
-	usermod -a -G adm ${VAR_UG_PKG_NAME}
 	chown ${VAR_UG_PKG_NAME}:adm /var/log/${VAR_UG_PKG_NAME}
 	chmod 0750 /var/log/${VAR_UG_PKG_NAME}
 }
@@ -743,4 +745,75 @@ pkgos_register_endpoint_postinst () {
 	else
 		db_unregister ${PKG_NAME}/keystone-admin-password
 	fi
+}
+
+# Before removing the package, ask if we should remove the db
+# Prototype: pkgos_prerm_db_clean ${1} <template-prefix> <package-name>
+# Example:   pkgos_prerm_db_clean ${1} neutron neutron-common
+pkgos_prerm_db_clean () {
+	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME
+	PKPRM_TEMPLATE_PREFIX=${1}
+	PKPRM_PACKAGE_NAME=${2}
+	shift
+	shift
+	DPKG_COMMAND=${1}
+
+	if [ "${1}" = "remove" ] ; then
+		. /usr/share/debconf/confmodule
+
+		# We unregister the value, since we don't want to use
+		# debconf as a register, and prefer a volatile thing.
+		db_unregister ${PKPRM_TEMPLATE_PREFIX}/configure_db
+		db_input ${PKPRM_TEMPLATE_PREFIX}/configure_db || true
+		db_get ${PKPRM_TEMPLATE_PREFIX}/configure_db
+		if [ "$RET" = "true" ]; then
+			if [ -e /usr/share/dbconfig-common/dpkg/prerm ] ; then
+				. /usr/share/dbconfig-common/dpkg/prerm
+				dbc_go ${neutron-common} $@
+			fi
+		fi
+	fi
+}
+
+# Perform dbconfig-common cleanups when removing a package
+# Prototype: pkgos_postrm_db_clean <template-prefix-name> <package-name> $@
+# Example:   pkgos_postrm_db_clean neutron                neutron-common $@
+pkgos_postrm_db_clean () {
+	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME
+	PKPRM_TEMPLATE_PREFIX=${1}
+	PKPRM_PACKAGE_NAME=${2}
+	shift
+	shift
+        # Purge db on purge
+        if [ -f /usr/share/debconf/confmodule ] ; then
+                . /usr/share/debconf/confmodule
+                db_get ${PKPRM_TEMPLATE_PREFIX}/configure_db
+                if [ "$RET" = "true" ] ; then
+                        if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
+                                . /usr/share/dbconfig-common/dpkg/postrm
+                                dbc_go ${PKPRM_PACKAGE_NAME} $@
+                        else
+                                rm -f /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
+                                if which ucf >/dev/null 2>&1; then
+                                        ucf --purge /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
+                                        ucfr --purge ${PKPRM_PACKAGE_NAME} /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
+                                fi
+                        fi
+                fi
+        fi
+}
+
+# Perform cleanups when removing a package
+# Prototype: pkgos_postrm <template-prefix-name> <package-name> $@
+# Example:   pkgos_postrm neutron                neutron-common $@
+pkgos_postrm () {
+	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME
+	pkgos_postrm_db_clean $@
+
+	PKPRM_TEMPLATE_PREFIX=${1}
+	PKPRM_PACKAGE_NAME=${2}
+	shift
+	shift
+
+	rm -rf /var/lib/${PKPRM_TEMPLATE_PREFIX} /var/log/${PKPRM_TEMPLATE_PREFIX} /var/lock/${PKPRM_TEMPLATE_PREFIX}
 }
