Don't attempt to grep anything if there's no config file in pkgos_read_admin_creds

diff --git a/pkgos_func b/pkgos_func
--- a/pkgos_func
+++ b/pkgos_func
@@ -303,21 +303,25 @@ pkgos_read_admin_creds () {
 	PKG_NAME=${2}
 	SECTION=${3}
 
-	if grep -q auth_host ${CONF_FNAME} ; then
-		pkgos_read_config ${CONF_FNAME} auth_host         ${PKG_NAME}/auth-host         ${SECTION}
+	if [ ! -r "${CONF_FNAME}" ] ; then
+		db_input high ${PKG_NAME}/auth-host || true
 	else
-		# This is needed for l3_agent.ini
-		if grep -q auth_url ${CONF_FNAME} ; then
-			pkgos_get_config ${CONF_FNAME} auth_url ${SECTION}
-			NO_PROTO=${RET#http://}
-			BEFORE_PORT=$(echo ${NO_PROTO} | cut -d":" -f1)
-			if [ -z "${BEFORE_PORT}" ] ; then
-				db_set ${PKG_NAME}/auth-host ${BEFORE_PORT}
-			fi
-			db_input high ${PKG_NAME}/auth-host || true
-			db_go
+		if grep -q auth_host ${CONF_FNAME} ; then
+			pkgos_read_config ${CONF_FNAME} auth_host         ${PKG_NAME}/auth-host         ${SECTION}
 		else
-			echo "Couldn't find either auth_host or auth_url :("
+			# This is needed for l3_agent.ini
+			if grep -q auth_url ${CONF_FNAME} ; then
+				pkgos_get_config ${CONF_FNAME} auth_url ${SECTION}
+				NO_PROTO=${RET#http://}
+				BEFORE_PORT=$(echo ${NO_PROTO} | cut -d":" -f1)
+				if [ -z "${BEFORE_PORT}" ] ; then
+					db_set ${PKG_NAME}/auth-host ${BEFORE_PORT}
+				fi
+				db_input high ${PKG_NAME}/auth-host || true
+				db_go
+			else
+				echo "Couldn't find either auth_host or auth_url :("
+			fi
 		fi
 	fi
 
