Use NODEPOOL_MIRROR_HOST instead of httpredir.debian.org
Change-Id: I884e1062b9a13a58abedbae245470c7a259cfc9e

diff --git a/build-tools/pkgos-infra-install-sbuild b/build-tools/pkgos-infra-install-sbuild
--- a/build-tools/pkgos-infra-install-sbuild
+++ b/build-tools/pkgos-infra-install-sbuild
@@ -17,8 +17,17 @@ BUILDER_SYS_USERNAME="jenkins"
 BUILDER_HOMEDIR=/home/jenkins
 GITREPO_ROOT=${WORKSPACE}
 
+if ! [ -r /etc/nodepool/provider ] ; then
+    echo "Could not read /etc/nodepool/provider"
+    exit 1
+else
+    . /etc/nodepool/provider
+    NODEPOOL_MIRROR_HOST=${NODEPOOL_MIRROR_HOST:-mirror.$NODEPOOL_REGION.$NODEPOOL_CLOUD.openstack.org}
+    NODEPOOL_MIRROR_HOST=$(echo $NODEPOOL_MIRROR_HOST|tr '[:upper:]' '[:lower:]')
+fi
+
 # Some configuration stuff
-CLOSEST_DEBIAN_MIRROR=http://httpredir.debian.org/debian
+CLOSEST_DEBIAN_MIRROR=http://${NODEPOOL_MIRROR_HOST}/debian
 
 PATH=/usr/bin:/usr/sbin:/bin:/sbin
 APT="DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends"
